<!DOCTYPE html>
<html>
<head>
    <title>Good Stock Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }
        
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        
        .company-info {
            text-align: center;
            margin-bottom: 30px;
        }
        
        .report-date {
            text-align: right;
            margin-bottom: 20px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        
        th, td {
            border: 1px solid #000;
            padding: 8px 12px;
            text-align: left;
        }
        
        th {
            background-color: #f2f2f2;
        }
        
        .text-right {
            text-align: right;
        }
        
        .text-center {
            text-align: center;
        }
        
        .footer {
            margin-top: 50px;
            text-align: center;
        }
        
        @media print {
            body {
                padding: 0;
                margin: 10mm;
            }
            
            .no-print {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div class="no-print" style="text-align: right; margin-bottom: 20px;">
        <button onclick="window.print()">Print Report</button>
        <button onclick="window.close()">Close</button>
    </div>
    
    <div class="company-info">
        <h2>PT. Your Company Name</h2>
        <p>Jl. Company Address Street No. 123, City, Province</p>
        <p>Phone: (021) 1234-5678 | Email: info@yourcompany.com</p>
    </div>
    
    <h1>LAPORAN GOOD STOCK</h1>
    
    <div class="report-date">
        <p>Tanggal Cetak: {{ date('d M Y H:i:s') }}</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>No.</th>
                <th>Kode Barang</th>
                <th>Nama Barang</th>
                <th>Good Stock</th>
                <th>Satuan</th>
            </tr>
        </thead>
        <tbody>
            @forelse($stocks as $index => $stock)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td>{{ $stock->kode_barang }}</td>
                    <td>{{ $stock->nama_barang }}</td>
                    <td class="text-right">{{ number_format($stock->good_stock, 2) }}</td>
                    <td>{{ $stock->satuan }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="text-center">No stock data available</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>© {{ date('Y') }} PT. Your Company Name. All rights reserved.</p>
        <p>Generated by Inventory Management System</p>
    </div>
    
    <script>
        // Auto print when page loads
        window.onload = function() {
            setTimeout(function() {
                window.print();
            }, 500);
        };
    </script>
</body>
</html>